/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { default as RequestCertificateScriptJson } from "../RequestCertificate.ral.json";

export const RequestCertificate = new ExecutableScript<{
  contract: HexString;
  args: HexString;
}>(Script.fromJson(RequestCertificateScriptJson, ""));
